---
- hosts: tomcat
  remote_user: root
  become: yes
  tasks:
  - name: installing tomcat
    package:
      name: tomcat
      state: present
  - name: stopping tomcat
    service:
      name: tomcat
      status: down
  - name: configuration of tomcat
    copy:
      src: /root/tomcat.config
      dest: /etc/tomcat/tomcat-users.xml
  - name: starting up tomcat
    service:
      name: tomcat
      state: started
  - name: copying addressbook file
    copy:
      src: /root/jenkins/workspace/step1/addressbook_main/target/addressbook.war
      dest: /usr/share/tomcat/webapps
