---
- hosts: tomcat
  remote_user: root
  become: yes
  tasks:
  - name: installing tomcat
    package:
      name: tomcat
      state: present
    when:  ansible_facts['os_family'] == "RedHat"
  - name: installing tomcat
    package:
      name: tomcat9
      state: present
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting tomcat
    service:
      name: tomcat
      state: started
    when:  ansible_facts['os_family'] == "RedHat"
  - name: configuration of tomcat
    copy:
      src: /root/tomcat.config
      dest: /etc/tomcat/tomcat-users.xml
    when:  ansible_facts['os_family'] == "RedHat"
  - name: configuration of tomcat
    copy:
      src: /root/tomcat.config
      dest: /etc/tomcat9/tomcat-users.xml
    when:  ansible_facts['os_family'] == "Debian"
  - name: starting up tomcat
    service:
      name: tomcat
      state: restarted
    when:  ansible_facts['os_family'] == "RedHat"
  - name: installing tomcat
    package:
      name: tomcat9
      state: restarted
    when:  ansible_facts['os_family'] == "Debian"
  - name: copying addressbook file
    copy:
      src: /root/jenkins/workspace/step1/addressbook_main/target/addressbook.war
      dest: /usr/share/tomcat/webapps
